import type { HeroWeatherData } from './types'

export const heroWeather: HeroWeatherData = {
  location: 'Shanghai',
  condition: '晴',
  temperature: 32,
  dateLabel: '10月1日',
  weekday: '周四',
  forecasts: [
    {
      id: 'today',
      label: '今天',
      date: '10月1日',
      kind: 'partly-cloudy',
      condition: '多云',
      precipitation: 60,
      high: 36,
      low: 24,
    },
    {
      id: 'tomorrow',
      label: '明天',
      date: '10月2日',
      kind: 'partly-cloudy',
      condition: '多云',
      precipitation: 60,
      high: 32,
      low: 23,
    },
    {
      id: 'saturday',
      label: '周六',
      date: '10月3日',
      kind: 'rain',
      condition: '雨',
      precipitation: 60,
      high: 32,
      low: 23,
    },
    {
      id: 'sunday',
      label: '周日',
      date: '10月4日',
      kind: 'thunder',
      condition: '雷阵雨',
      precipitation: 80,
      high: 29,
      low: 21,
    },
    {
      id: 'monday',
      label: '周一',
      date: '10月5日',
      kind: 'thunder',
      condition: '雷阵雨',
      precipitation: 60,
      high: 26,
      low: 17,
    },
  ],
}
